Problem 1
Assignment 6
Jared Schlak - Applied Algorithms

Problem 1
1.Given an integer n(1 <= n <= 10^5), find the minimum number of 1’s required to obtain n if
you are allowed to hit the following three functions in any order any number of times . Desired
time Complexity (O(n2)), desired space complexity (O(n)).

In [248]:
def main(n):
    dict1 = {1:1}
    while n >= len(dict1):
        i = 1
        curr = len(dict1) + 1
        min = curr
        while i < curr / 2 +1:
            if dict1[i] + dict1[curr - i] < min:
                min = dict1[i] + dict1[curr - i]
            i += 1
        for i in range(2, curr//2 + 1):
            if curr % i == 0:
                if dict1[i] + dict1[int(curr/i)] < min:
                    min = dict1[i] + dict1[curr/i]
        strcurr = str(curr)
        minsplit = 0
        if len(strcurr) > 1:
            for i in range(1, len(strcurr)):
                try:
                    if strcurr[i] != "0":
                        minsplit = dict1[int(strcurr[:i])] + dict1[int(strcurr[i:])]
                        if minsplit < min:
                            min = minsplit
                except:
                    pass
                    
            
        dict1.update({curr : min})
    print(dict1[n])
main(22)
    

4


Problem 2
Assignment 6
Jared Schlak - Applied Algorithms

Problem 2
A robot can only walk in one of the four directions (left, right, top, bottom). The grid it is walking
on is labeled with characters of the English alphabet. The programmers of the robot have now
constrained its motion further. It can step from a grid cell A to grid cell B, if the character on cell
A is less than the character on cell B.
The ordering on the characters is the lexicographic ordering.
Write a program that computes the maximum number of steps that the robot can take starting
at any grid cell.

In [240]:
def max_steps(grid):

    rows = len(grid)
    cols = len(grid[0])
    
    
    grid_results = [[0 for _ in range(cols)] for _ in range(rows)]
    
    for x in range(rows*cols):
        for i in range(rows):
            for j in range(cols):
                try:
                    if grid[i][j] < grid[i+1][j]:
                        grid_results[i][j] = 1 + int(grid_results[i+1][j])
                except:
                    pass
                try:
                    if grid[i][j] < grid[i-1][j]:
                        grid_results[i][j] = 1 + int(grid_results[i-1][j])
                except:
                    pass
                try:
                    if grid[i][j] < grid[i][j+1]:
                        grid_results[i][j] = 1 + int(grid_results[i][j+1])
                except:
                    pass
                try:
                    if grid[i][j] < grid[i][j-1]:
                        grid_results[i][j] = 1 + int(grid_results[i][j-1])
                except:
                    pass      

    for x in range(rows*cols):
        for i in range(rows):
            for j in range(cols):
                max = 0
                try:
                    if grid[i][j] < grid[i+1][j]:
                        if grid_results[i+1][j] > max:
                            max = grid_results[i+1][j]
                            grid_results[i][j] = 1 + max
                except:
                    pass
                try:
                    if grid[i][j] < grid[i-1][j]:
                        if grid_results[i-1][j] > max:
                            max = grid_results[i-1][j]
                            grid_results[i][j] = 1 + max
                except:
                    pass
                try:
                    if grid[i][j] < grid[i][j+1]:
                        if grid_results[i][j+1] > max:
                            max = grid_results[i][j+1]
                            grid_results[i][j] = 1 + max
                except:
                    pass
                try:
                    if grid[i][j] < grid[i][j-1]:
                        if grid_results[i][j-1] > max:
                            max = grid_results[i][j-1]
                            grid_results[i][j] = 1 + max
                except:
                    pass
                
    print(grid_results)
    max_number = 0
    for i in range(rows):
        for j in range(cols):
            if grid_results[i][j] > max_number:
                max_number = grid_results[i][j]
    return max_number
            

max_steps([["t","o","y"],["c","a","t"],["t","o","p"]])

[[1, 2, 0], [2, 4, 1], [0, 3, 2]]


4

Problem 3
Assignment 6
Jared Schlak - Applied Algorithms

Problem 3
Pushpa, a professional thief, wanted to steal coconuts from forest.In the forest the coconut trees
are in a straight line. Each tree has a certain number of coconuts, the only constraint is that if
you rob from the adjacent coconut trees, an alert will be sent to the forest officials who will arrest
Pushpa. Write a program to find the maximum number of coconuts pushpa can steal without
getting caught.

In [249]:
import math

def get_max_coconuts(nums):

    
    rows = len(nums)+2
    cols = math.ceil(len(nums)/2)+1
    m = [[0 for i in range(cols)] for i in range(rows)]
    
    for i in range(rows - 2):
        m[i+2][0] = nums[i]
        
    maxnum = nums[0]    
    for i in range(rows - 2):
        if nums[i] > maxnum:
            maxnum = nums[i]
        m[i+2][1] = maxnum
        
    for j in range(cols):
        m[0][j] = j
    for j in range(cols):
        m[1][j] = m[1][0]
    for j in range(cols):
        m[2][j] = m[2][0]
        
    
    for i in range(3,rows):
        for j in range(2, cols):
            m[i][j] = max(m[i-1][j],m[i][j-1],m[i-2][j-1]+m[i][0])
                
    print(m)
    return m[i][j]
get_max_coconuts([2, 7, 9, 3, 1])

[[0, 1, 2, 3], [0, 0, 0, 0], [2, 2, 2, 2], [7, 7, 7, 7], [9, 9, 11, 11], [3, 9, 11, 11], [1, 9, 11, 12]]


12

Problem 4
Assignment 6
Jared Schlak - Applied Algorithms

Problem 4
Ujwala has given a list of non-negative integers and a target, the task is to find the sum of sub
list numbers which are divisible by target and return those list of numbers. If sum is not found
in list return empty list.

In [250]:
def subset_divisible(A, target):
    rows = len(A) + 2
    cols = target + 2
    m = [[0 for i in range(cols)] for i in range(rows)]
    
    
    for i in range(rows-2):
        m[i+2][0] = A[i]
    for i in range(rows-2):
        m[i+2][1] = True
        
    for j in range(1, cols):
        if j == 1:
            m[1][j] = True 
        else:
            m[1][j] = False 
    
    for j in range(1, cols - 1):
        m[0][j+1] = j
   

    
    for i in range(2,rows):
        for j in range(2, cols):
            if (m[i-1][j] == True):
                m[i][j] = True
            elif m[i][0] <= j-1:
                if (m[i-1][j-(m[i][0])]==True):
                    m[i][j] = True
                else:
                    m[i][j] = False
            else:
                m[i][j] = False
    
    array = []
    while m[i][j] == True:
        i -= 1
        if j == 1:
            break
        if m[i][j] == False:
            array.append(m[i+1][0])
            j = j - (m[i+1][0])
              
    return(array)
    
subset_divisible([3, 1, 7, 5], 6)

[5, 1]

In [251]:
def get_max_sbstr(s, c1, c2):
    array = []
    for char in s:
        if char == c1 or char == c2:
            array.append(char)
    c1_count = 0
    c2_count = 0
    for char in array:
        if char == c1:
            c1_count += 1
        elif char == c2:
            c2_count += 1
    newarray = []
    if c1 > c2:
        newarray += array
        newarray += c2
    else:
        newarray += c1
        newarray += array
    
    print(newarray)
    
    dict_max_sub = {0:0}
    count_c1 = 0
    for i in range(0, len(newarray)):
        try:
            if newarray[i] == c2:
                dict_max_sub[i] = dict_max_sub[i-1] + count_c1
            elif newarray[i] == c1:
                count_c1 += 1
                dict_max_sub[i] = dict_max_sub[i-1]
        except:
            pass
                    
    print(dict_max_sub)
    return dict_max_sub[i]

get_max_sbstr("bcedecd", "b", "d")

['b', 'b', 'd', 'd']
{0: 0, 1: 0, 2: 2, 3: 4}


4

Problem 6
Assignment 6
Jared Schlak - Applied Algorithms

Problem 6
It is the year 11984 (yes, 11984), and the world is a dystopian society.
After decades of searching, the resistance has finally found Rick Sanchez’s Portal Gun which
lets them open portals to anywhere in the universe. This will be their key to winning the "war".
Unfortunately, the Portal Gun is password protected, and they need your help to crack the pass-
word.
You know that the password is obtained by deleting some digits from the password file which
you obtained from the Portal Gun’s Persistent Random Access Memory (PRAM). The password
file is just a list of decimal digits. Note that the password cannot be empty!
As a first step, you would like to find the total number of possible passwords. Write a program
that computes the number of passwords.
Full credit only for the most efficient solution.

In [253]:
import numpy as np

def num_passwords(digit_list):
    size = len(digit_list) + 1
    m = np.identity(size)
    
    for i in range(0,size-1):
        m[i+1][0]=digit_list[i]
                
    for j in range(0, size):
        m[0][j] = j
        
    count = 1
    m[1][1] = 1
    for i in range(2, size):
        count += 1
        if m[i][0]  in digit_list[:i-1]:
            count = count - 1
            m[i][1] = count
            
        else:
            m[i][1] = count
            
    for i in range(3, size):
        for j in range(2, size):
            if i > j:
                if m[i][1] > m[i-1][1]:
                    m[i][j] = m[i-1][j-1]+m[i-1][j]
                else:
                    t = i
                    while m[i][0] != m[t-1][0]:
                        t = t -1
                    if t - 2 == 0:
                        m[i][j] = m[i-1][j-1]+m[i-1][j]
                    else:
                        m[i][j] = m[i-1][j-1]+m[i-1][j] - m[t-2][j-1]
    
    
    print(m)
                
    ans = (sum(m[i])-m[i][0])
    return int(ans)



num_passwords([1, 2, 1, 3])

[[0. 1. 2. 3. 4.]
 [1. 1. 0. 0. 0.]
 [2. 2. 1. 0. 0.]
 [1. 2. 3. 1. 0.]
 [3. 3. 5. 4. 1.]]


13